### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rafaelarcanjo** [cloudcmd/gritty#13]
I'm trying to build with cloudcmd and gritty, but I always get an error, according to the log:

```
2310 verbose stack Exit status 1
2310 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2310 verbose stack     at EventEmitter.emit (events.js:315:20)
2310 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2310 verbose stack     at ChildProcess.emit (events.js:315:20)
2310 verbose stack     at maybeClose (internal/child_process.js:1048:16)
2310 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2311 verbose pkgid node-pty@0.10.0
2312 verbose cwd /var/www/html
2313 verbose Linux 4.19.0-14-amd64
2314 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "gritty" "-g"
2315 verbose node v14.16.1
2316 verbose npm  v6.14.12
2317 error code ELIFECYCLE
2318 error errno 1
2319 error node-pty@0.10.0 install: `node scripts/install.js`
2319 error Exit status 1
2320 error Failed at the node-pty@0.10.0 install script.
2320 error This is probably not a problem with npm. There is likely additional logging output above.
2321 verbose exit [ 1, true ]
```

Cloudcmd has already been installed using NPM and is running normally.

**Comment by coderaiser** [comment]
It can be related to `python` or `c++` compiler according to [node-pty](https://github.com/microsoft/node-pty#linux-apt).
Do you have it installed?

**Comment by rafaelarcanjo** [comment]
Yes
```
root@4a3c1577b512:/var/www/html/node-pty# npm list | grep node
node-pty@0.10.0 /var/www/html/node-pty
+-- @types/node@12.20.10
| +-- node-environment-flags@1.0.6
```

**Comment by coderaiser** [comment]
What version of `python` do you have?

**Comment by rafaelarcanjo** [comment]
```
root@4a3c1577b512:/var/www/html/node-pty# python --version
Python 2.7.16
```

**Comment by coderaiser** [comment]
It can be a problem with `npm` itself.
Could you try to upgrade `npm` to `v7` with:

```sh
npm i npm -g
```

**Comment by rafaelarcanjo** [comment]
The installation worked, but now there is an error in the execution

```
www-data@039829aab1bb:~$ cloudcmd --no-open --root /var/www/html -a -u root -p root --prefix cloudcmd --terminal 
root: /var/www/html
cloudcmd --terminal: The argument 'id' must be a non-empty string. Received ''
url: http://0.0.0.0:8000/cloudcmd/
```

**Comment by coderaiser** [comment]
According to [terminal docs](http://cloudcmd.io/#terminal), `--terminal-path` should be added as well, because it installed as separate application, try:

```sh
cloudcmd --no-open --root /var/www/html -a -u root -p root --prefix cloudcmd  --terminal --terminal-path `gritty --path` --save
```

Is it works for you?

**Comment by rafaelarcanjo** [comment]
No. I tested it with the full command too
```
root@039829aab1bb:/var/www/html# cloudcmd --no-open --root /var/www/html -a -u root -p root --prefix cloudcmd  --terminal --terminal-path `gritty --path` --save
root: /var/www/html
cloudcmd --terminal: The argument 'id' must be a non-empty string. Received ''
url: http://0.0.0.0:8000/cloudcmd/
```

**Comment by coderaiser** [comment]
Could you please tell me what Linux do you use?

**Comment by rafaelarcanjo** [comment]
OpenSuse Lead 15.2. But I am associated in Docker with Debian 10 image

**Comment by coderaiser** [comment]
Unfortunately I can't reproduce this. Could you please try to install `node-pty` and try [example](https://github.com/microsoft/node-pty#example-usage) listed in it's repo.

Is it works good, or the same problem?

**Comment by rafaelarcanjo** [comment]
If you want to reproduce

```
docker run -d --rm --name test -p 8000:8000 alfasoft/php:7.1
docker exec -it name bash
/usr/bin/cloudcmd --terminal
```

**Comment by rafaelarcanjo** [comment]
If you want to reproduce I did the build on this image of the docker
`docker run -d --rm -p 8000:8000 alfasoft/php:7.1`
I really appreciate your help

**Comment by coderaiser** [comment]
`alfasoft/php` has a lot file layers, maybe this is the reason, I have no ability to run it right now.

Here is officially supported [Docker](http://cloudcmd.io/#docker) images:
- `coderaiser/cloudcmd`
- `coderaiser/cloudcmd-alpine`

They are based on `debian` and `alpine` accordingly. Could you please try one of them using:

```sh
docker run -t --rm -v ~:/root -v /:/mnt/fs -w=/root -p 8000:8000 coderaiser/cloudcmd
```

Both of them has enabled `terminal` by default.

**Comment by rafaelarcanjo** [comment]
In the image provided the error was displayed and did not load the gritty
```
docker run -d -t --rm -v ~:/root -v /:/mnt/fs -w=/root -p 8000:8000 -p 8001:8001 -p 1337:1337 coderaiser/cloudcmd
root@260f1eb15fc3:/# node /usr/src/app/bin/cloudcmd.mjs --port 8001 --terminal --terminal-path `gritty --path` --save
cloudcmd --terminal: The argument 'id' must be a non-empty string. Received ''
```

**Comment by rafaelarcanjo** [comment]
My solution:

```
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt install  -y --no-install-recommends nodejs
COPY --from=coderaiser/cloudcmd:14.3.3-x64 /usr/src/app /usr/src/app
COPY config.json /usr/src/app/json/config.json
node /usr/src/app/bin/cloudcmd.js -u $CLOUDCMD_USERNAME -p $CLOUDCMD_PASSWORD &
```

Thanks for help!
