### ISSUE TITLE
Can not install on termux

### ISSUE THREAD

**Issue by maytinhdibo** [cloudcmd/gritty#7]
I'm trying to install gritty on Termux but some error. This's log.
```clang-8: error: linker command failed with exit code 1 (use -v to see invocation) make: * [pty.target.mk:135: Release/obj.target/pty.node] Error 1 make: Leaving directory '/data/data/com.termux/files/home/MDE/node_modules/node-pty/build' gyp ERR! build error gyp ERR! stack Error: make failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:200:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) gyp ERR! System Linux 4.14.85-16003457 gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /data/data/com.termux/files/home/MDE/node_modules/node-pty gyp ERR! node -v v12.4.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok npm WARN nodejs@1.0.0 No repository field. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"android","arch":"arm64"})```

**Comment by coderaiser** [comment]
Looks like it's relates to https://github.com/microsoft/node-pty.
